// UserActionTypes.js
const USERS_API_CALL_REQUEST = 'USERS_API_CALL_REQUEST'
const USERS_API_CALL_SUCCESS = 'USERS_API_CALL_SUCCESS'
const USERS_API_CALL_FAILURE = 'USERS_API_CALL_FAILURE'


// export user actions types
const UserActionTypes = {
  USERS_API_CALL_REQUEST,
  USERS_API_CALL_SUCCESS,
  USERS_API_CALL_FAILURE,
}

export default UserActionTypes
